language: java
jdk:
  - openjdk8
branches:
  only:
    - main

# Travis CI Server's Home
cache:
  - directories:
      - '$HOME/.m2/repository'
      - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r SpringBootWebService *
  - mkdir -p deploy
  - mv SpringBootWebService.zip deploy/SpringBootWebService.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: qazyj-springboot-build #S3 버킷 이름
    region: ap-northeast-2
    skip_cleanup: true
    acl: private #zip 파일 접근 private으로
    local_dir: deploy #before_deploy에서 생성한 디렉토리
    wait_until_deployed : true
    on:
      branch: main # 새롭게 추가된 부분

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - qazyj@naver.com
