language: java
jdk:
  - openjdk8
branches:
  only:
    - main

# Travis CI Server's Home
cache:
  - directories:
      - '$HOME/.m2/repository'
      - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r SpringBootWebService *
  - mkdir -p deploy
  - mv SpringBootWebService.zip deploy/SpringBootWebService.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: qazyj-springboot-build #S3 버킷 이름
    region: ap-northeast-2
    skip_cleanup: true
    acl: private #zip 파일 접근 private으로
    local_dir: deploy #before_deploy에서 생성한 디렉토리
    wait_until_deployed : true
    on:
      branch: main

## 새롭게 추가된 부분
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: qazyj-springboot-build # S3 버킷
    key: springboot2-webservice.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip # 압축 확장자
    application: springboot2-webservice # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: springboot2-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      branch: main
## 새롭게 추가된 부분

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - qazyj@naver.com
